name: Kavenegar Action
description: Repository stats SMS notifier
author: Sadra Yahyapour

branding:
  icon: message-square
  color: gray-dark

runs:
  using: docker
  image: Dockerfile

inputs:
  github_token:
    description: The GitHub auth token
    default: ${{ github.token }}
    required: true

  repository:
    description: The repository name in the form of "<owner>/<repo>"
    default: ${{ github.repository }}
    required: true

  api_key:
    description: the API key from your dashboard
    required: true

  receptor:
    description: the reciever phone numbere
    required: true

  message:
    description: message context
    default: hello world
    required: true
